int_struc_percentage = 0.1
length_constant = 0.85
width_constant = 0.09
height_constant = 0.09
AC_chord_ratio = 0.25
nose_ratio = 0.15
wing_ac_to_tail_ac = 0.88
# wing_ac_from_nose = length * 0.15 + wing.chord_root * 0.25
# tail_ac_from_nose = wing_ac_from_nose + wing.wing_span * 0.25
# wing_ac_to_tail_ac = tail_ac_from_nose - wing_ac_from_nose